--select CAST([TimeStamp] AS DATETIME) AS STAMP  FROM XR70CX_1

/*DECLARE @UnixDate BIGINT = 1644809278
SELECT CAST(DATEADD(ms,CAST(RIGHT(@UnixDate,3) AS SMALLINT),
DATEADD(s,@UnixDate / 1000,'1970-01-01')) AS DATETIME2(3)) AS DateTimes*/

--CONVERT TIMESTAMP TO DATETIME--
SELECT DATEADD(S, CONVERT(int, LEFT([TimeStamp],10)),'1970-01-01') AS [DateTime] FROM XR70CX_1

/*CREATE FUNCTION dbo.ConvertUnixToDateTime(@Datetime BIGINT)
RETURNS DATETIME
AS
BEGIN 
    RETURN (SELECT DATEADD(second,@Datetime, CAST('1970-01-01' AS datetime)))
END;
GO

SELECT dbo.ConvertUnixToDateTime([TimeStamp]) AS DATETIMES FROM XR70CX_1*/
