CREATE TABLE USERS_MANAGEMENTS(
	[USERID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ASSIGNOR] VARCHAR(50) NULL,
	[USERNAME] CHAR(20) NOT NULL,
	[PASSWORD] VARCHAR(MAX) NOT NULL,
	[DISPLAY] VARCHAR(50) NULL,
	[PERMISSION] VARCHAR(MAX) NULL,
	[POSITION] CHAR(20) NULL,
	[ADDTIME] VARCHAR(50) NULL,
	[EDITTIME] VARCHAR(50) NULL,
	[EDITED] VARCHAR(50) NULL,
);
